{% set name = "croc" %}
{% set version = "10.2.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/schollz/croc/archive/v{{ version }}.tar.gz
  sha256: 993e0bb72e79c5168d78db5c14d84f69beeab819ab4d06f4d98fcddd23487207

build:
  number: 0

requirements:
  build:
    - {{ compiler('go-nocgo') }}
    - go-licenses

test:
  commands:
    - croc --help

about:
  home: https://github.com/schollz/croc
  license: MIT
  license_file:
    - LICENSE
    - license-files/
  summary: Securely send things from one computer to another
  dev_url: https://github.com/schollz/croc

extra:
  recipe-maintainers:
    - danielnachun
