{% set name = "croc" %}
{% set version = "10.2.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/schollz/croc/archive/v{{ version }}.tar.gz
  sha256: c259c07b9da3ea39726b0c5e3f78ae66e858e1379bdb11bef93d31298e68f5fe

build:
  number: 0

requirements:
  build:
    - {{ compiler('go-nocgo') }}
    - go-licenses

test:
  commands:
    - croc --help

about:
  home: https://github.com/schollz/croc
  license: MIT
  license_file:
    - LICENSE
    - license-files/
  summary: Securely send things from one computer to another
  dev_url: https://github.com/schollz/croc

extra:
  recipe-maintainers:
    - danielnachun
