{% set name = "croc" %}
{% set version = "10.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/schollz/croc/archive/v{{ version }}.tar.gz
  sha256: 78bf0efd00daa9002bcdeb460f4ddaf82dde4480e63862feab0958ed9ed54963

build:
  number: 0

requirements:
  build:
    - {{ compiler('go-nocgo') }}
    - go-licenses

test:
  commands:
    - croc --help

about:
  home: https://github.com/schollz/croc
  license: MIT
  license_file:
    - LICENSE
    - license-files/
  summary: Securely send things from one computer to another
  dev_url: https://github.com/schollz/croc

extra:
  recipe-maintainers:
    - danielnachun
