schema_version: 1

context:
  version: "11.1.0"

package:
  name: croc
  version: ${{ version }}

source:
  url: https://github.com/schollz/croc/archive/v${{ version }}.tar.gz
  sha256: ae71b65f54c48fd2f4d60bb0209a0a18584bb0c744967675b0a0d4f2ffb22e8f

build:
  number: 0

requirements:
  build:
    - ${{ compiler('go-nocgo') }}
    - go-licenses

tests:
  - script:
      - croc --help

about:
  license: MIT
  license_file:
    - LICENSE
    - license-files/
  summary: Securely send things from one computer to another
  homepage: https://github.com/schollz/croc
  repository: https://github.com/schollz/croc

extra:
  recipe-maintainers:
    - danielnachun
