schema_version: 1

context:
  version: "11.2.5"

package:
  name: croc
  version: ${{ version }}

source:
  url: https://github.com/schollz/croc/archive/v${{ version }}.tar.gz
  sha256: f26633248287928f1af8755bd92bf366af5feaf10e4bba0ce53f7ad2c57b3372

build:
  number: 0

requirements:
  build:
    - ${{ compiler('go-nocgo') }}
    - go-licenses

tests:
  - script:
      - croc --help

about:
  license: MIT
  license_file:
    - LICENSE
    - license-files/
  summary: Securely send things from one computer to another
  homepage: https://github.com/schollz/croc
  repository: https://github.com/schollz/croc

extra:
  recipe-maintainers:
    - danielnachun
