schema_version: 1

context:
  version: "11.2.1"

package:
  name: croc
  version: ${{ version }}

source:
  url: https://github.com/schollz/croc/archive/v${{ version }}.tar.gz
  sha256: c3e276f46755f2984cb7958cbe00e01ecf85351d2509d45067b6291abc404d29

build:
  number: 0

requirements:
  build:
    - ${{ compiler('go-nocgo') }}
    - go-licenses

tests:
  - script:
      - croc --help

about:
  license: MIT
  license_file:
    - LICENSE
    - license-files/
  summary: Securely send things from one computer to another
  homepage: https://github.com/schollz/croc
  repository: https://github.com/schollz/croc

extra:
  recipe-maintainers:
    - danielnachun
